### ISSUE TITLE
Feature request: view with most recent podcast episodes

### ISSUE THREAD

**Issue by DiogoConstantino** [ubuntu-flutter-community/musicpod#28]
I believe this to be a very common use case:

Users to looking for recent episodes of all the podcasts they subscribed. In order to do this the best way is to have a view/window displaying an ordered list of the most recent episodes for all the podcasts they subscribed, so that users can avoid to check each of them, and to miss, or forget or disable desktop notifications.

So what I'm requesting is for there to be a single window where there's such ordered list of the most recent podcasts episodes for all the subscribed podcasts.

**Comment by Feichtmeier** [comment]
Good idea
I believe this could be shown  as the first page before the charts?

Or in a tab view?

Your Podcasts | Explore 

?

**Comment by DiogoConstantino** [comment]
It should be before first page if the user as already subscribed to a podcast.

**Comment by Feichtmeier** [comment]
hm, rethinking about this, I think I will stick to the library = sidebar approach
because the app is a trinity of local music, podcasts and radio. you can pin albums, podcasts, stations or your own playlists to the sidebar.
For new episodes I already show a desktop notifications. I will also add a colored dot for podcasts with updates. 
I hope you do not have a strong veto here 😸 Best regards

**Comment by Feichtmeier** [comment]
Like this @DiogoConstantino 

![grafik](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/c9421cab-be76-4b26-bf69-2801ed9ffa73)

**Comment by Feichtmeier** [comment]
@DiogoConstantino added a library view for now

![grafik](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/e5e67cd6-e7fc-4588-9cba-503029fc4382)

I'll work on some indicator for new episodes or filter

**Comment by Feichtmeier** [comment]
@DiogoConstantino 

Update should be on the edge channel now 😁
