### ISSUE TITLE
Add a choice on where to source podcasts.

### ISSUE THREAD

**Issue by Parzzix** [ubuntu-flutter-community/musicpod#416]
I believe you currently source podcast information from itunes. I was wondering if an option to source from Itunes or the [Podcast Index](https://podcastindex.org/). The last being a bit more freedom loving and all. 

Thanks, and Happy New Year!

**Comment by Feichtmeier** [comment]
Closed by #485

However Since musicpod is open source and run inside a snap container I currently have no option to insert this into the snap via github actions for both AMD64 and ARM so I wait for this to insert my personal credentials in github secrets

However podcast index is free and you can just create an account
then in the settings you can safe them
![grafik](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/1ff0cd03-e839-4dee-a36c-094b9ecc9aac)
restart and use them from then on
