### ISSUE TITLE
i could not add some podcasts. and there is not option to edit/update - added radio station link, kindly resolve it.

### ISSUE THREAD

**Issue by leefordjudes** [ubuntu-flutter-community/musicpod#602]
i used to get podcast & radio stations - links from spotify like websites and I some Christian websites.
some websites change their links often.  here I faced some issue. 
so I add this issue. 

1. i could not add some podcasts. 
2. there is not option to edit/update - added radio station link, 
        kindly resolve it.

1. i could not add some podcasts. 
![1](https://github.com/ubuntu-flutter-community/musicpod/assets/13608248/9b48dec7-9fe2-4389-bed7-fa345af176b2)
![2](https://github.com/ubuntu-flutter-community/musicpod/assets/13608248/243051f7-cc39-4c73-b47b-2c5962c1e8df)
![3](https://github.com/ubuntu-flutter-community/musicpod/assets/13608248/b17457f0-1b6c-4182-a91e-a0f1038a47b8)
![4](https://github.com/ubuntu-flutter-community/musicpod/assets/13608248/1e982d8a-e11a-46e7-bf91-4db9bd980854)
![5](https://github.com/ubuntu-flutter-community/musicpod/assets/13608248/264ef8b8-9458-46e1-878d-90489b517108)

2. there is not option to edit/update - added radio station link, 
![image](https://github.com/ubuntu-flutter-community/musicpod/assets/13608248/ee2e2ece-095e-4fc0-92bc-c652b2758b76)

**Comment by Feichtmeier** [comment]
podcasts need to find discoverable on itunes or podcast index

there are quite a bunch podcasts nowadays which are only on spotify

if you can find them on itunes or podcast index you can find them here
![image](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/10f0385f-d15a-4102-83ad-e26f8eb19d3d)

or add them manually

but if they are only on spotify this wont work, as the spotify api is not being used here, for legal reasons I dont want to open this can of worms

for the radio station link, I can add an edit button

**Comment by leefordjudes** [comment]
kindly add edit button for radio station link. 
i am awaiting for that.

**Comment by Feichtmeier** [comment]
> kindly add edit button for radio station link. i am awaiting for that.

Hi 👋 I gave it a second thought but...
This is not how this app is actually designed to be used.
You should use the radio search to find your station. If it is really one of the very very very few radio streams that is not discoverable with https://www.radio-browser.info/ (which the radio part of this app is designed around) then you need to add it manually, because your station maybe just doesnt want you to add it manually and want to promote their app or whatever, none of my business. If you want to change the URL, you need to unstar (⭐-Button) it, and add it again with your new URL

This is how the radio functionality has been designed:

https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/36314477-8188-4c54-a366-becac56d846d
