### ISSUE TITLE
Is it be possible to have default desktop font as interface font?

### ISSUE THREAD

**Issue by rago666** [ubuntu-flutter-community/musicpod#62]
Many user use different fonts as their interface font (I use inter for example).  Can musicpod use this default font as interface font instead of ubuntu? 

Install method: Snapstore
Distro: Fedora kde spin

I am really enjoying the app, it is very snappy 😉 and the podcast integration is really amazing. Have a good day.

**Comment by Feichtmeier** [comment]
Hi @rago666 great that you are enjoying MusicPod :smile_cat: 
using several other libraries we created for our flutter apps here
regarding the font it is specifically [yaru.dart](https://github.com/ubuntu/yaru.dart)
Would you mind opening an issue about this on that repository?
I think this would be something for many apps. But this won't be easy I fear since the Ubuntu font is bundled in yaru.dart
Eventually we could bundle some popular fonts in there that are common in linux desktops, let's see what the others think :crossed_fingers:

**Comment by Feichtmeier** [comment]
Closing because this cant be fixed here
