### ISSUE TITLE
Weird visual artifacts when window is maximized

### ISSUE THREAD

**Issue by rene-coty** [ubuntu-flutter-community/musicpod#747]
I use Musicpod as a flatpak (version 1.4.1) on Fedora 40 / GNOME 46.
When I maximize the window and a song / radio is playing, the bottom of the app (the player) will display several glitches like duplicated and greyed out buttons, a buggy gradient,…

I couldn't record it, because my screen recorder doesn't seem to capture these artifacts -it will only display a black zone instead (which at least indicates there's something wrong ^^')

[Capture vidéo du 2024-05-17 18-59-58.webm](https://github.com/ubuntu-flutter-community/musicpod/assets/95506494/0426f7d8-fbd3-4a6d-8539-48eda6e8c8ea)

**Comment by rene-coty** [comment]
A more descriptive video I managed to take with a phone
https://github.com/ubuntu-flutter-community/musicpod/assets/95506494/4261027d-b79d-42aa-85aa-d5c33b5933f5

**Comment by Feichtmeier** [comment]
Oh :( is this the flatpak? 
thanks for the report

**Comment by TheShadowOfHassen** [comment]
Id bet my boots this is the same as the other issue. I have a job I have to do but im working on figuring this out.

**Comment by Feichtmeier** [comment]
Btw thanks for using MusicPod @rene-coty 
Awesome to have Fedora users now

**Comment by rene-coty** [comment]
Thanks for your quick replies! This bug only occurs when using the 'maximize' button in the top-right corner, not when resizing with the mouse. When it is in a maximized state, the player at the bottom will turn into some semi-transparent widget and magical things might happen (multiple mouse pointers sometimes…)

Another video : 

https://github.com/ubuntu-flutter-community/musicpod/assets/95506494/391cd040-3dbd-4934-81e5-e35c5d4769da

**Comment by Feichtmeier** [comment]
yeah its a missing graphic bit! @TheShadowOfHassen will work on it when he has time
some parts seem to be missing that are in the snap but not the flatpak (mesa... drivers... etc)

**Comment by TheShadowOfHassen** [comment]
@rene-coty , can you show me the output of flatpak run org.feichtmeier.Musicpod?

**Comment by rene-coty** [comment]
It displays the following lines:

`OnLoad`
`package:media_kit_libs_linux registered.`
`media_kit: VideoOutput: video_output_new: 5136412915792`
`Cannot load libcuda.so.1`
`media_kit: VideoOutput: Using H/W rendering.`
`flutter: VideoOutput.Resize`
`flutter: {handle: 5136412915792, id: 5136229717392, rect: {left: 0, top: 0, width: 1, height: 1}}`
`flutter: NativeVideoController: Texture ID: 5136229717392`

**Comment by TheShadowOfHassen** [comment]
That's what I got from a fedora install, and a Manjaro install, but not from Ubuntu which I test it on.

I'm going to ask around. I'll let you know what I find out!

**Comment by TheShadowOfHassen** [comment]
@rene-coty could you tell me what version of flatpak you're running (flatpak --version)

**Comment by rene-coty** [comment]
1.15.8

**Comment by TheShadowOfHassen** [comment]
I'm working on diagnosing the problem, but I've run into some problems. I will try to fix this, but it may take a while. Thank you for your patience !

**Comment by TheShadowOfHassen** [comment]
@rene-coty what graphic drivers are you running, and do you have x11 or wayland?

**Comment by rene-coty** [comment]
I just found and copy-pasted these information from GNOME Control Center:

# Rapport d’informations du système
---

## Détails du compte rendu
- **Date de génération :**                         2024-05-20 09:38:59

## Informations liées au matériel :
- **Modèle du matériel :**                         Acer Aspire A315-23
- **Mémoire :**                                    8,0 Gio
- **Processeur :**                                 AMD Athlon Silver 3050U with Radeon™ Graphics × 2
- **Carte graphique :**                            AMD Radeon™ Graphics
- **Capacité du disque :**                         256,1 Go

## Informations liées au logiciel :
- **Version du micrologiciel :**                   V1.15
- **Nom du système d’exploitation :**              Fedora Linux 40 (Workstation Edition)
- **Construction du système d’exploitation :**     (null)
- **Type de système d’exploitation :**             64 bits
- **Version de GNOME :**                           46
- **Système de fenêtrage :**                       Wayland
- **Version du noyau :**                           Linux 6.8.9-300.fc40.x86_64

And here is the output of `lspci -n -n -k | grep -A 2 -e VGA -e 3D` (which should print video drivers in use)

```
05:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] [1002:15d8] (rev cd)
	Subsystem: Acer Incorporated [ALI] Device [1025:1456]
	Kernel driver in use: amdgpu
--
05:00.7 Non-VGA unclassified device [0000]: Advanced Micro Devices, Inc. [AMD] Raven/Raven2/Renoir Non-Sensor Fusion Hub KMDF driver [1022:15e6]
	Subsystem: Acer Incorporated [ALI] Device [1025:1456]
	Kernel driver in use: i2c_amd_mp2

```

**Comment by TheShadowOfHassen** [comment]
I've discovered that this issue affects not only Fedora but the latest Debian testing and Manjaro. 

Furthermore if I build Musicpod from source using this patched version: Branch (https://github.com/ubuntu-flutter-community/musicpod/tree/mk_test) PR: https://github.com/ubuntu-flutter-community/musicpod/pull/761) I get the same issue.

NOTE: you have to use that patched version because you need the git version of mediakitvideo to work on newer systems. 
NOTE2: I only tested the source build on Debian, but I'm getting the same problem, so I assume it'll require the same solution. (Hopefully)

Therefore, I can conclude that this probably isn't a Flatpak problem, but is something else between Flutter and the system.

@Feichtmeier has informed me of plans to port Musicpod to the next version of Flutter that just released a few days ago. It'll take some time to get to Musicpod because he needs to port the Yaru toolkit first. It's possible that this flutter update could fix the problem, so I'm going to wait until then and see.

If that doesn't fix it my best guess is its either a problem with libhandy (I think the bottom thing is a libhandy widget?) or flutter. Currently, I lean towards a flutter issue, but we'll see then. 


@rene-coty,  I'm sorry, but this issue is going to take a while to fix, I have to wait for the new flutter port. If you need a musicplayer until then I suggest Rhytmnbox, It doesn't look nearly as good as musicpod, but it has a lot of the same features.

**Comment by TheShadowOfHassen** [comment]
With the latest flatpak version, the problem is fixed. @rene-coty, I'd love to know if it fixed your problem!

**Comment by rene-coty** [comment]
Yep it's fixed :D
