### ISSUE TITLE
Hide "more options" and "favorite"

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/musicpod#754]
Under Local Audio the "more options" arrow and the "favorites" icon could be hidden until mouseover. This is similar to Spotify and it helps unclutter the page.

This example is not so cluttered because the titles are short:
![screenshot](https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/9076c3cb-d62a-4561-9bb9-0afe1856f106)

**Comment by Feichtmeier** [comment]
I played around with this idea a while ago but found it less handy and also it's tricky to keep the performance good then but I'll have another look

**Comment by Feichtmeier** [comment]
https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/ded97a6a-7204-4a3e-806c-efed97cc3ef4

hmhm... kinda gives me some ADHS vibes here 😵 
also I need to check on hover if I liked a song or not :S

**Comment by madsrh** [comment]
> hmhm... kinda gives me some ADHS vibes here 😵

😆  I don't get that kind of vibes, but I see what you mean.

> also I need to check on hover if I liked a song or not :S

No no, the favorits are visible ❤️  

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/39be0d9e-b803-4882-947a-5a3d5e3a2f09)

**Comment by Feichtmeier** [comment]
ah, hm... I think it looks more cleaner when staring at it, and in youtubemusic this is also similar, but I am not sure if this is so good for accessability (focus with tab), but that is a nightmare with flutter anyways currently so that is not really a strong argument. I'll have another try on this soon (did you tag your music yet? use musicbrainz)

**Comment by Feichtmeier** [comment]
this is now fixed
