### ISSUE TITLE
Radio Browser information suppressed.

### ISSUE THREAD

**Issue by ben2talk** [ubuntu-flutter-community/musicpod#929]
I hope this does not come across as being harsh in any way...  Overall I love the appearance of MusicPod, it imports my music quickly.

Whilst there is a lot to LIKE about musicpod, but this is an issue I found when firing it up and looking into RADIO (for which I currently use a .m3u playlist which opens with Strawberry, QMPlay2, or any other player).

Example - Adroit Jazz Underground.

First of all, there are many available streams... from mp3/320k, OGG/192k.

When available, obviously (to me) Ogg Opus is supreme in terms of quality and low  bandwidth.

A search in MusicPod reveals what - 'Adroit Jazz Und..' and a 'choice' of 7 identical icons with truncated information (no option for a detailed list).

For this reason, other applications work better for searching and MusicPod appears rather more like an eyecandy application dumbed down for Ubuntu users with no option to reveal vital information.

Examples:

QMPlay2: [QMPlay2: https://i.imgur.com/LgdIdXn.png](https://i.imgur.com/VHHp5Kt.png)

Strawberry: https://i.imgur.com/KCtnqgN.png

I hope that this is interesting, or useful.

**Comment by Feichtmeier** [comment]
> I hope this does not come across as being harsh in any way...  Overall I love the appearance of MusicPod, it imports my music quickly.
> 
> Whilst there is a lot to LIKE about musicpod, but this is an issue I found when firing it up and looking into RADIO (for which I currently use a .m3u playlist which opens with Strawberry, QMPlay2, or any other player).
> 
> Example - Adroit Jazz Underground.
> 
> First of all, there are many available streams... from mp3/320k, OGG/192k.
> 
> When available, obviously (to me) Ogg Opus is supreme in terms of quality and low  bandwidth.
> 
> A search in MusicPod reveals what - 'Adroit Jazz Und..' and a 'choice' of 7 identical icons with truncated information (no option for a detailed list).
> 
> For this reason, other applications work better for searching and MusicPod appears rather more like an eyecandy application dumbed down for Ubuntu users with no option to reveal vital information.
> 
> Examples:
> 
> QMPlay2: [QMPlay2: https://i.imgur.com/LgdIdXn.png](https://i.imgur.com/VHHp5Kt.png)
> 
> Strawberry: https://i.imgur.com/KCtnqgN.png
> 
> I hope that this is interesting, or useful.
> 
> 
> 

Hey thanks for your issue
Sure that's interesting and probably because my personal fav radio station (6forty radio) only provides one stream this certainly somehow slipped under the rug 
Maybe, apart from showing more info about the stream, the results should be shown inside a list rather than a grid?

**Comment by Feichtmeier** [comment]
@ben2talk how is this?

![grafik](https://github.com/user-attachments/assets/1a85eadf-1139-4d54-99b1-183f30fd2fb2)

**Comment by ben2talk** [comment]
Colour me impressed - that looks really good.

"this certainly somehow slipped under the rug"

I noticed once or twice with other projects that some really obvious things are not spotted.

The best place to hide somebody's nose is right between their eyes ;)

**Comment by Feichtmeier** [comment]
> Colour me impressed - that looks really good.
> 
> "this certainly somehow slipped under the rug"
> 
> I noticed once or twice with other projects that some really obvious things are not spotted.
> 
> The best place to hide somebody's nose is right between their eyes ;)

It's always the best for features when people actually using the features spot things
MusicPod is a triple feature app with podcasts, local collection and radio so if I don't design things from the start correctly sometimes it takes a while until I notice it or never ^^
Feel free to open any other issue you find best regards (since I wrongly stored stations by URL instead of uuid your pinned radio stations will be needed to pin again since I can't reuse this, I don't know which operating system you are using but in case it's Ubuntu and the snap you can try this feature from the edge channel, otherwise you need to wait until the next stable release)
